version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elastic
    environment:
      - node.name=elastic
      - cluster.initial_master_nodes=elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - type: bind
        source: ./esdata
        target: /usr/share/elasticsearch/data
    networks:
      - esnetwork
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    ports:
      - "5601:5601"
    networks:
      - esnetwork
    depends_on:
      - elasticsearch
  transactions-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5000:80"
    networks:
        - esnetwork
volumes:
    esdata:
networks:
    esnetwork:
        driver: bridge